const $ = s => document.querySelector(s);
const files = $('#files'), drop = $('#drop'), work = $('#work'), list = $('#list');
const canvas = document.createElement('canvas'); let items = [], ratio = null;
const fa = n => String(n).replace(/\d/g, d => '۰۱۲۳۴۵۶۷۸۹'[d]);
function add(fileList) { items = []; list.innerHTML = ''; [...fileList].filter(f => f.type.startsWith('image/')).forEach(file => { const url = URL.createObjectURL(file), image = new Image(); image.onload = () => { items.push({file,image,url}); const row = document.createElement('div'); row.className = 'file'; row.innerHTML = `<img src="${url}"><span>${file.name} · ${fa(image.naturalWidth)}×${fa(image.naturalHeight)}</span>`; list.append(row); work.hidden = false; }; image.onerror = () => URL.revokeObjectURL(url); image.src = url; }); }
files.onchange = () => add(files.files); drop.ondragover = e => e.preventDefault(); drop.ondrop = e => { e.preventDefault(); add(e.dataTransfer.files); };
$('#quality').oninput = e => $('#qv').textContent = fa(e.target.value) + '٪'; document.querySelectorAll('.presets button').forEach((b,i) => b.onclick = () => { ratio = i ? Number(b.dataset.r) : null; document.querySelectorAll('.presets button').forEach(x => x.classList.remove('active')); b.classList.add('active'); });
$('#clear').onclick = () => { items.forEach(x => URL.revokeObjectURL(x.url)); items=[]; list.innerHTML=''; work.hidden=true; files.value=''; $('#status').textContent=''; };
function dimensions(im) { let w=im.naturalWidth,h=im.naturalHeight; if(ratio){if(w/h>ratio)w=Math.round(h*ratio);else h=Math.round(w/ratio);} return {w,h}; }
const encode = (type,q) => new Promise(resolve => canvas.toBlob(resolve,type,q));
async function compress(im,type,q,limit){const d=dimensions(im);canvas.width=d.w;canvas.height=d.h;const ctx=canvas.getContext('2d',{alpha:type==='image/png'});ctx.clearRect(0,0,d.w,d.h);if(type!=='image/png'){ctx.fillStyle='#fff';ctx.fillRect(0,0,d.w,d.h);}ctx.drawImage(im,0,0,d.w,d.h);let out=await encode(type,q);if(!out)throw new Error('فرمت خروجی پشتیبانی نمی‌شود');if(type!=='image/png'&&out.size>limit){let lo=.1,hi=q,best=out;for(let i=0;i<10;i++){const mid=(lo+hi)/2,candidate=await encode(type,mid);if(candidate.size<=limit){best=candidate;lo=mid;}else hi=mid;}out=best;}return out;}
$('#export').onclick=async()=>{if(!items.length)return;const type=$('#format').value,q=Number($('#quality').value)/100,requested=Number($('#target').value),ext=type==='image/png'?'png':type==='image/jpeg'?'jpg':type==='image/avif'?'avif':'webp';$('#status').textContent='در حال فشرده‌سازی واقعی...';let total=0;try{for(const x of items){const out=await compress(x.image,type,q,requested?requested*1024:Math.max(1024,x.file.size*.7));total+=out.size;const a=document.createElement('a');a.href=URL.createObjectURL(out);a.download=x.file.name.replace(/\.[^.]+$/,'')+'-optimized.'+ext;document.body.appendChild(a);a.click();a.remove();await new Promise(r=>setTimeout(r,150));}$('#status').textContent=`${fa(items.length)} تصویر آماده شد · حجم خروجی: ${fa(Math.max(1,Math.round(total/1024)))} KB`;}catch(e){$('#status').textContent=e.message||'پردازش ناموفق بود';}};
